# -*- mode: ruby -*-
# vi: set ft=ruby :

# Define the VMs
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Master VM
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.10.10"
    master.vm.network "forwarded_port", guest: 6443, host: 6443, protocol: "tcp"
    master.vm.network "forwarded_port", guest: 2379, host: 2379, protocol: "tcp"
    master.vm.network "forwarded_port", guest: 2380, host: 2380, protocol: "tcp"
    master.vm.network "forwarded_port", guest: 10250, host: 10250, protocol: "tcp"
    master.vm.network "forwarded_port", guest: 10255, host: 10255, protocol: "tcp"
    master.vm.network "forwarded_port", guest: "30000-32767", host: "30000-32767", protocol: "tcp"
  end

  # Node01 VM
  config.vm.define "node01" do |node01|
    node01.vm.hostname = "node01"
    node01.vm.network "private_network", ip: "192.168.10.11"
    node01.vm.network "forwarded_port", guest: 10250, host: 10251, protocol: "tcp"
    node01.vm.network "forwarded_port", guest: 10255, host: 10256, protocol: "tcp"
    node01.vm.network "forwarded_port", guest: "30000-32767", host: "30001-32768", protocol: "tcp"
  end

  # Node02 VM
  config.vm.define "node02" do |node02|
    node02.vm.hostname = "node02"
    node02.vm.network "private_network", ip: "192.168.10.12"
    node02.vm.network "forwarded_port", guest: 10250, host: 10252, protocol: "tcp"
    node02.vm.network "forwarded_port", guest: 10255, host: 10257, protocol: "tcp"
    node02.vm.network "forwarded_port", guest: "30000-32767", host: "30002-32769", protocol: "tcp"
  end

  # Bridge network
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.10.1"
end