# -*- mode: ruby -*-
# vi: set ft=ruby :

# Define the VMs
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Master VM
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.10.10"
  end

  # Node01 VM
  config.vm.define "node01" do |node01|
    node01.vm.hostname = "node01"
    node01.vm.network "private_network", ip: "192.168.10.11"
  end

  # Node02 VM
  config.vm.define "node02" do |node02|
    node02.vm.hostname = "node02"
    node02.vm.network "private_network", ip: "192.168.10.12"
  end

  # Bridge network
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.10.1"
end